add filter to sdk config
chargeafter-rnd/sdk pull request #1
Opened 2022-12-22 16:21 UTC by LiorCohenChargeAfter

2022-12-22 16:38 UTC, MurLuck commented
@kostat what do you think?

2022-12-22 19:38 UTC, kostat requested changes

2022-12-22 19:38 UTC, kostat commented on src/index.tsx
> +  filter?: IFilter;
Should not be part of the config, but passed to the prequalify/checkout APIs

2022-12-22 19:38 UTC, kostat commented on src/index.tsx
> +      filter: config.filter,
should be passed to the prequalify/checkout APIs

2022-12-26 07:01 UTC, kostat approved these changes

2022-12-26 07:22 UTC, merged